add_newline = false

format = """
$username\
$hostname\
$directory\
$docker_context\
$package\
$pulumi\
$vagrant\
$env_var\
$custom\
$sudo\
$fill\
$kubernetes\
$gcloud\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$nodejs\
$golang\
$python\
$rust\
$terraform\
$helm\
$line_break\
$jobs\
$status\
$character\
"""

right_format = """
$cmd_duration\
$time\
$memory_usage\
$battery\
"""

[fill]
symbol = " "

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜](bold red)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

[cmd_duration]
format = " [$duration]($style) "

# Disable the package module, hiding it from the prompt completely
[kubernetes]
disabled = false
format = '[$symbol$context(/$namespace)]($style) '
symbol = '󱃾 '

[battery]
full_symbol = '󰁹 '
charging_symbol = '󰂄 '
discharging_symbol = '󱊣 '

[[battery.display]]
threshold = 10
style = "bold red"
discharging_symbol = '󱊡 '

[[battery.display]]
threshold = 33
style = "bold red"
discharging_symbol = '󱊡 '

[[battery.display]]
threshold = 66
style = "bold yellow"
discharging_symbol = '󱊢 '

[[battery.display]]
threshold = 99
style = "bold green"
discharging_symbol = '󱊣 '

[[battery.display]]
threshold = 100
style = "bold green"

[time]
disabled = false
format = "[ $time]($style) "

[memory_usage]
disabled = false
threshold = 0
format = "[$symbol ${ram}( | ${swap})]($style) "
symbol = ""

[status]
disabled = false

[shell]
disabled = false

[hostname]
ssh_only = false
format = "[ $hostname]($style) "

[directory]
truncate_to_repo = false
format = "[]($style) [$path]($style)[$read_only]($read_only_style) "

[sudo]
disabled = false

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[git_commit]
tag_disabled = false
only_detached = false

[git_metrics]
disabled = false

[golang]
symbol = " "
format = "[$symbol($version )]($style)"

[helm]
format = "[$symbol($version )]($style)"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
format = "[$symbol($version )]($style)"

[terraform]
format = "[$symbol$version]($style) "

[aws]
format = '[$symbol ($profile )(\($region\) )(\[$duration\])]($style)'
symbol = ""
